### ISSUE TITLE
Reset password by username as well as email

### ISSUE THREAD

**Issue by wolph** [joshuachinemezu/django-rest-resetpassword#1]
First of all, great library. Thank you!

Second... it would be very useful to me if you could reset a password both by username and email. So effectively doing something like this for the user lookup:

```python
users = User.objects.filter(username__iexact=query) | User.objects.filter(email__iexact=query)
```

**Comment by joshuachinemezu** [comment]
This should resolve it #2

**Comment by wolph** [comment]
Thank you for the fix!
